
language: julia

os:
  - osx
  - linux

julia:
  - 1.0
  - 1.3
  - 1.4

python:
  - 3.5

notifications:
  email: false


script: # the default script is equivalent to the following
- julia examples/local_hh_neuron.jl
