
language: julia

services:
  - docker

os:
  - linux

julia:
  - 1.0
  - 1.3
  - 1.4

python:
  - 3.6

notifications:
  email: true


install:
- docker build -t spike .
script:
- docker run spike julia local_hh_neuron.jl
